asdf-community/asdf-golang

- bin/exec-env
Hello Kenny,
I just installed golang. Had to set GOPATH in `exec-env` to fix errors like below:
```
$ go get github.com/elazarl/goproxy
package github.com/elazarl/goproxy: cannot download, $GOPATH not set. For more details see: go help gopath
```
I'm not sure if this is the right thing to do (new to golang). I just followed conventions I previously used for other plugins (each version has it's packages in it's own install directory). Please do let me know if there is a better way to do this.
> Set GOPATH if not already set

- README.md
Adds a requirements section. Ubuntu 16.04 no longer uses curl by default. Could switch to wget?
Coming from: https://github.com/asdf-vm/asdf/pull/295
> Adding a Requirements section

- .travis.yml
- README.md
- bin/install
Golang offers ppc64le variant however this plugin does not support this platform.
For your information, here is my box spec:
```
$ uname -mr
5.4.12-200.fc31.ppc64le ppc64le # running RaptorCS Blackbird motherboard with IBM Power9 v2 8-core
$ asdf --version
v0.7.6-6207e42
```
```
$ asdf install golang 1.13.6
Platform 'linux' supported!
Arch 'ppc64le' not supported!
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   199  100   199    0     0    293      0 --:--:-- --:--:-- --:--:--   293
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
I confirm that this patch allow me to install the ppc64le version successfully.
```
$ go version
go version go1.13.6 …
```
> Support ppc64le architecture

- bin/install
For China users, sometimes the download speed from `https://storage.googleapis.com/golang` is really slow, but this one `https://dl.google.com/go` is always faster. After using dig, it shows `dl.google.com` is resolved to a server in Bejing, China. `storage.googleapis.com` is resolved to a server in the USA.
So this PR introduces a shell environment variable `BASE_URL`, so that users can specify an alternative base url to download the tarball.
> Able to specify an alternative url to install

- bin/parse-legacy-file
This updates the legacy file detection to find the most recent matching installed version of go. So for example if go.mod has `1.13` listed, and your system has `1.13.11` installed then the script will return `1.13.11` instead of `1.13`. 
Tested on Mac and Linux.
Fixes #33
> Find the most recent matching installed version

- bin/install
Fix error `Arch 'arm64' not supported!` during install on M1 ARM chip.
Note: since Go hasn't added proper support for macOS ARM the installation will still fail. Once support is added by Go maintainers, then this plugin should work, assuming the same download link format is used.
See: https://github.com/golang/go/issues/38485
> Support M1 ARM chip

- bin/install
Found `install_default_golang_pkgs()` performs `$ASDF_INSTALL_PATH/bin/asdf reshim`. `$ASDF_INSTALL_PATH` points directory where the specific version should be installed, so `asdf` should not be there.
Also, found that current asdf performs reshim for version of package (i.e. `asdf reshim <name> <version>` ) when plugin's `bin/install` returns success.
https://github.com/asdf-vm/asdf/blob/master/lib/commands/command-install.bash
> fix: invalid asdf path in `install_default_golang_pkgs()`

- bin/install
Default golang packages listed in `~/.default-golang-pkgs` will be installed unexpected directory when performing `asdf install golang <ver>` without setting `GOPATH` and `GOROOT`.
With changes in this PR, default golang packages should be installed under `$ASDF_INSTALL_PATH/packages` that is default `GOPATH` set in `bin/exec-env`.
> Set default GOPATH and GOROOT when installing default go pkgs

- .travis.yml
- bin/download
- bin/exec-env
- bin/install
- bin/list-all
- bin/parse-legacy-file
- lib/helpers.sh
Summary
-------------
- Creates a temporary directory if using an older version of asdf.
- Install delegates to `bin/download` if using an older version of asdf.
Notes
--------
`bin/download` description: https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md#bindownload
> Add `bin/download` per latest asdf guidelines

- bin/download
Hi, have been having a weird problem on macOS Big Sur:
```
verifying checksum
shasum: standard input: no properly formatted SHA checksum lines found
Authenticity of package archive can not be assured. Exiting.
```
I've seen varying [re](https://unix.stackexchange.com/a/561549)fe[re](https://thomask.sdf.org/blog/2019/05/05/techniques-for-verifying-shasums-conveniently.html#md5sumsha1sumsha256sum-coreutils:~:text=You%20have%20to%20type%20all%20this,like%20them.%20Very%20interesting%20history%20though.)nc[es](https://github.com/docker-library/memcached/pull/6/files) to this error online but no clear explanation as to what's going on. The solution seems to be to have two spaces between the `shasum` arguments. The reason this might be passing still in travis builds is that travis appears to be …
> Add extra space between shasum args

- bin/download
This PR adds one extra space for `sha256sum`. If this space is lacking, Alpine Linux `sha256sum` cannot work properly (also see https://github.com/gliderlabs/docker-alpine/issues/174): 
```
[hyperion@wizard test]$ sha256sum -c <<< "951a3c7c6ce4e56ad883f97d9db74d3d6d80d5fec77455c6ada6c1f7ac4776d2 go.tar.gz"
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
[hyperion@wizard test]$ sha256sum -c <<< "951a3c7c6ce4e56ad883f97d9db74d3d6d80d5fec77455c6ada6c1f7ac4776d2  go.tar.gz"
go.tar.gz: OK
```
but in the coreutils version an extra space doesn't break anything:
```
sam@wizard:/tmp % sha256sum --version
sha256sum (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: …
```
> Add extra space between sha256sum args

- bin/download
Hi! Thanks for your useful tools.
Try to download golang 1.15, which does not support m1 mac, output is the following.
```shell
$ asdf install golang 1.15.13
mkdir: /Users/w1mvy/.asdf/downloads/golang/1.15.13: File exists
Platform 'darwin' supported!
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1449  100  1449    0     0   7173      0 --:--:-- --:--:-- --:--:--  7173
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1449  100  1449    0     0   5138      0 --:--:-- --:--:-- --:--:--  5138
verifying checksum
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
Authenticity of package archive can not be …
```
> fail when download status 404 or 403

- README.md
- bin/parse-legacy-file
The go directive in go.mod files is of the format `major.minor`. This
commit will allow the highest installed version of go with the same
major component to be selected. The previous behaviour was to use the
highest installed version with the same major _and_ minor components,
but I don't think this was strictly necessary. It is valid to use go
1.16 to build a project whose go.mod declares "go 1.14", for example.
For packages within the module, the compiler should reject use of
language features introduced after the version specified by the go
directive.
I think this adheres more closely to the expected behaviour of programs
that parse `go.mod`, and asdf users who need to pin a particular minor
or patch version of go can use `.tool-versions` or `.go-version`.
Source: …
> Use highest matching minor version from go.mod

- README.md
This patch adds documentation for the ASDF_GOLANG_DEFAULT_PACKAGES_FILE variable introduced in #59 (I neglected to include this there—sorry about that).
> Document ASDF_GOLANG_DEFAULT_PACKAGES_FILE

- bin/install
Like the title suggests, this should update the default packages command to use `go install` for go versions 1.16 and higher as it is now the command to be used when downloading a module to be run as a binary: https://go.dev/blog/go116-module-changes
The `go_version` variable _should_ be set correctly, I assumed the `"$ASDF_INSTALL_VERSION"` variable was in the form of `X.X.X` without any other parts to it, if that's incorrect let me know and I can update it
> Updated the default packages command to use "go install" for versions 1.16+

- bin/exec-env
This file is not strict-mode compliant and because of that, if you execute it from a script in strict mode, it will throw an error like follows:
```bash
WARN Failed to discover go env: failed to run 'go env': exit status 1
ERRO Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: /Users/myuser/.asdf/plugins/golang/bin/exec-env: line 4: GOROOT: unbound variable
```
> Make exec-env strict-mode compliant

- bin/parse-legacy-file
asdf v0.11.0 introduced a change that causes and infinate recurse when calling `asdf list golang` from `parse-legacy-file` as noted in issue #83 and [asdf/1372](https://github.com/asdf-vm/asdf/issues/1372).
This fixes #83.
> Don't call back into `asdf list golang`

- README.md
- bin/download
> Add ASDF_GOLANG_SKIP_CHECKSUM to skip verifying checksum.

- bin/download
Hi, I tried to use asdf-golang for my FreeBSD to run into error:
(with `set -x`)
```
devbsd% asdf install  golang  latest          
mkdir: /home/windymelt/.asdf/downloads/golang/1.19: File exists
Platform 'freebsd' supported!
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  141M  100  141M    0     0  10.3M      0  0:00:13  0:00:13 --:--:-- 10.6M
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0    240      0 --:--:-- --:--:-- --:--:--   241
verifying checksum
+ local archive_file_name=/home/windymelt/.asdf/downloads/golang/1.19/archive.tar.gz
+ local …
```
> Use process substitution to adapt FreeBSD's sha256sum

- bin/list-legacy-filenames
- bin/parse-legacy-file
Go workspaces were introduced in Go 1.18: https://go.dev/blog/get-familiar-with-workspaces
They list a go version, so we can use them in the same way as go.mod
> Use `go.work` in the same way as `go.sum`

- README.md
- bin/list-legacy-filenames
This changes the behavior of `bin/list-legacy-file` to allow users to set `ASDF_GOLANG_MOD_VERSION` to determine the inclusion of `go.mod` and `go.work`. As discussed in #99 upstream `asdf` has determined that the current behavior is not desirable, so we are starting down the path of deprecation.
> Add support for ASDF_GOLANG_MOD_VERSION

- set-env.zsh
Hello, I've recently started using this project in combination with direnv and noticed a small improvement. What's happening is the following
1. I **cd** into a directory with a .envrc file
2. Any command that's executed within this directory will always trigger an **direnv: unloading** hook
After some research, I found that this issue was related to **set-env.zsh** and the use of **absolute_dir_path**. In fact, I found a similar issue which was resolved:
https://github.com/halcyon/asdf-java/pull/144
In summary, the fix uses zsh's built in functionality to get the absolute dir path. This makes **absolute_dir_path** obsolete 🙂.
> Use built-in zsh function to get absolute dir path for golang

- README.md
I also updated the command from `asdf plugin-add` to `asdf plugin add` to match the official documentation.
Reference:
https://asdf-vm.com/manage/plugins.html
> Update installation and CI status url to match repo url

- README.md
`.` is deprecated, so replace it with `source` command.
ref: https://fishshell.com/docs/current/cmds/source.html
> . (a single period) is an alias for the source command. The use of . is deprecated in favour of source, and . will be removed in a future version of fish.
> Change command for fish in README.md

- lib/helpers.sh
The official golang site now makes riscv64 builds available for linux. This adds the correct `uanem -m` match in the helper. Tested on a Banana Pi BPI-F3 running Ubuntu 20.04, worked like a charm.
> Add riscv64 support since builds are now available

- README.md
- bin/exec-env
- bin/install
- bin/list-bin-paths
This PR includes two changes:  
- Improves README instructions to better guide new users.  
- Ensures that GOBIN is always set and used consistently, preventing binaries from being installed in unexpected locations.  
closes #151 
closes #150
> fix: improve setup instructions and enforce consistent GOBIN usage  
